<a href="https://colab.research.google.com/github/heydi98-hl/datawarehouse-seguros/blob/main/Aseguradoras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 16.4 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

In [2]:
from sqlalchemy import create_engine

In [3]:
import pandas as pd

In [4]:
database_url = "postgresql://etl_aseguradoras_xhzk_user:oi5ecQdH2xADCoNDerEt0PVODnKVAFS0@dpg-d6u5b4euk2gs7396o210-a.oregon-postgres.render.com/etl_aseguradoras_xhzk"

In [5]:
engine = create_engine("postgresql://etl_aseguradoras_xhzk_user:oi5ecQdH2xADCoNDerEt0PVODnKVAFS0@dpg-d6u5b4euk2gs7396o210-a.oregon-postgres.render.com/etl_aseguradoras_xhzk")

In [6]:
test = pd.read_sql("SELECT 1", engine)

In [7]:
print(test)

   ?column?
0         1

In [8]:
url = "https://raw.githubusercontent.com/heydi98-hl/etl-data-pipeline/refs/heads/main/aseguradoras.csv"

In [9]:
df = pd.read_csv(url)

In [10]:
df.head()

  id_tipo_seguro;tipo;categoria;riesgo_base
0                         1;Pyme;Familiar;-
1           2;Industrial;Empresarial; 4.68
2                3;Industrial;Familiar;5.10
3                 4;Industrial;Personal;N/A
4                  5;Auto;empresarial ;9.07

In [11]:
df.shape

(12, 1)

In [12]:
df.columns

Index(['id_tipo_seguro;tipo;categoria;riesgo_base'], dtype='object')

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 1 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   id_tipo_seguro;tipo;categoria;riesgo_base  12 non-null     object
dtypes: object(1)
memory usage: 228.0+ bytes

In [14]:
df.isnull().sum()

id_tipo_seguro;tipo;categoria;riesgo_base    0
dtype: int64

In [15]:
clientes = df.copy()

In [16]:
clientes.columns = clientes.columns.str.strip().str.lower()

In [17]:
for col in clientes.select_dtypes(include='object').columns:

    clientes[col] = clientes[col].astype(str).str.strip()

In [18]:
clientes = clientes.replace(r'^\s*$', pd.NA, regex=True)

In [25]:
clientes = clientes.drop_duplicates()

In [31]:
def motivo(row):
    motivos = []

In [36]:
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_aseguradoras_xhzk_user:oi5ecQdH2xADCoNDerEt0PVODnKVAFS0@dpg-d6u5b4euk2gs7396o210-a.oregon-postgres.render.com/etl_aseguradoras_xhzk"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Requirement already satisfied: psycopg2-binary in /usr/local/lib/python3.12/dist-packages (2.9.11)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
   ?column?
0         1